# Generated by Django 4.2.3 on 2023-07-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('ticker', models.CharField(max_length=6)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='wStockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Watcher15',
            fields=[
                ('stock_watcher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wStocks_main.stock_watcher')),
            ],
            bases=('wStocks_main.stock_watcher',),
        ),
        migrations.CreateModel(
            name='Stock_Watcher30',
            fields=[
                ('stock_watcher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wStocks_main.stock_watcher')),
            ],
            bases=('wStocks_main.stock_watcher',),
        ),
        migrations.CreateModel(
            name='Stock_Watcher60',
            fields=[
                ('stock_watcher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wStocks_main.stock_watcher')),
            ],
            bases=('wStocks_main.stock_watcher',),
        ),
    ]
